// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

public interface CreatePropertieResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CreatePropertieResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.proto.Propertie propertie = 1;</code>
   * @return Whether the propertie field is set.
   */
  boolean hasPropertie();
  /**
   * <code>.proto.Propertie propertie = 1;</code>
   * @return The propertie.
   */
  proto.Propertie getPropertie();
  /**
   * <code>.proto.Propertie propertie = 1;</code>
   */
  proto.PropertieOrBuilder getPropertieOrBuilder();
}
