// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

public interface DeletePropertieRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.DeletePropertieRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 propertieId = 1;</code>
   * @return The propertieId.
   */
  int getPropertieId();
}
