// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

public interface ListAllPropertieResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListAllPropertieResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto.Propertie propertie = 1;</code>
   */
  java.util.List<proto.Propertie> 
      getPropertieList();
  /**
   * <code>repeated .proto.Propertie propertie = 1;</code>
   */
  proto.Propertie getPropertie(int index);
  /**
   * <code>repeated .proto.Propertie propertie = 1;</code>
   */
  int getPropertieCount();
  /**
   * <code>repeated .proto.Propertie propertie = 1;</code>
   */
  java.util.List<? extends proto.PropertieOrBuilder> 
      getPropertieOrBuilderList();
  /**
   * <code>repeated .proto.Propertie propertie = 1;</code>
   */
  proto.PropertieOrBuilder getPropertieOrBuilder(
      int index);
}
