// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

public interface ListAllPropertieRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ListAllPropertieRequest)
    com.google.protobuf.MessageOrBuilder {
}
