// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

/**
 * Protobuf type {@code proto.Propertie}
 */
public  final class Propertie extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.Propertie)
    PropertieOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Propertie.newBuilder() to construct.
  private Propertie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Propertie() {
    title_ = "";
    address_ = "";
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Propertie();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Propertie(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            title_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            address_ = s;
            break;
          }
          case 32: {

            numberBedroom_ = input.readInt32();
            break;
          }
          case 40: {

            numberGarage_ = input.readInt32();
            break;
          }
          case 48: {

            buildingArea_ = input.readInt32();
            break;
          }
          case 56: {

            landArea_ = input.readInt32();
            break;
          }
          case 65: {

            value_ = input.readDouble();
            break;
          }
          case 72: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.PropertieOuterClass.internal_static_proto_Propertie_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.PropertieOuterClass.internal_static_proto_Propertie_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.Propertie.class, proto.Propertie.Builder.class);
  }

  /**
   * Protobuf enum {@code proto.Propertie.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>HOUSE = 1;</code>
     */
    HOUSE(1),
    /**
     * <code>APARTMENT = 2;</code>
     */
    APARTMENT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>HOUSE = 1;</code>
     */
    public static final int HOUSE_VALUE = 1;
    /**
     * <code>APARTMENT = 2;</code>
     */
    public static final int APARTMENT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return HOUSE;
        case 2: return APARTMENT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.Propertie.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Propertie.Type)
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private volatile java.lang.Object title_;
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMBERBEDROOM_FIELD_NUMBER = 4;
  private int numberBedroom_;
  /**
   * <code>int32 numberBedroom = 4;</code>
   * @return The numberBedroom.
   */
  public int getNumberBedroom() {
    return numberBedroom_;
  }

  public static final int NUMBERGARAGE_FIELD_NUMBER = 5;
  private int numberGarage_;
  /**
   * <code>int32 numberGarage = 5;</code>
   * @return The numberGarage.
   */
  public int getNumberGarage() {
    return numberGarage_;
  }

  public static final int BUILDINGAREA_FIELD_NUMBER = 6;
  private int buildingArea_;
  /**
   * <code>int32 buildingArea = 6;</code>
   * @return The buildingArea.
   */
  public int getBuildingArea() {
    return buildingArea_;
  }

  public static final int LANDAREA_FIELD_NUMBER = 7;
  private int landArea_;
  /**
   * <code>int32 landArea = 7;</code>
   * @return The landArea.
   */
  public int getLandArea() {
    return landArea_;
  }

  public static final int VALUE_FIELD_NUMBER = 8;
  private double value_;
  /**
   * <code>double value = 8;</code>
   * @return The value.
   */
  public double getValue() {
    return value_;
  }

  public static final int TYPE_FIELD_NUMBER = 9;
  private int type_;
  /**
   * <code>.proto.Propertie.Type type = 9;</code>
   * @return The enum numeric value on the wire for type.
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.proto.Propertie.Type type = 9;</code>
   * @return The type.
   */
  public proto.Propertie.Type getType() {
    @SuppressWarnings("deprecation")
    proto.Propertie.Type result = proto.Propertie.Type.valueOf(type_);
    return result == null ? proto.Propertie.Type.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!getAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, address_);
    }
    if (numberBedroom_ != 0) {
      output.writeInt32(4, numberBedroom_);
    }
    if (numberGarage_ != 0) {
      output.writeInt32(5, numberGarage_);
    }
    if (buildingArea_ != 0) {
      output.writeInt32(6, buildingArea_);
    }
    if (landArea_ != 0) {
      output.writeInt32(7, landArea_);
    }
    if (value_ != 0D) {
      output.writeDouble(8, value_);
    }
    if (type_ != proto.Propertie.Type.NONE.getNumber()) {
      output.writeEnum(9, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getTitleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!getAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, address_);
    }
    if (numberBedroom_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, numberBedroom_);
    }
    if (numberGarage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, numberGarage_);
    }
    if (buildingArea_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, buildingArea_);
    }
    if (landArea_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, landArea_);
    }
    if (value_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, value_);
    }
    if (type_ != proto.Propertie.Type.NONE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.Propertie)) {
      return super.equals(obj);
    }
    proto.Propertie other = (proto.Propertie) obj;

    if (getId()
        != other.getId()) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (getNumberBedroom()
        != other.getNumberBedroom()) return false;
    if (getNumberGarage()
        != other.getNumberGarage()) return false;
    if (getBuildingArea()
        != other.getBuildingArea()) return false;
    if (getLandArea()
        != other.getLandArea()) return false;
    if (java.lang.Double.doubleToLongBits(getValue())
        != java.lang.Double.doubleToLongBits(
            other.getValue())) return false;
    if (type_ != other.type_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + NUMBERBEDROOM_FIELD_NUMBER;
    hash = (53 * hash) + getNumberBedroom();
    hash = (37 * hash) + NUMBERGARAGE_FIELD_NUMBER;
    hash = (53 * hash) + getNumberGarage();
    hash = (37 * hash) + BUILDINGAREA_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingArea();
    hash = (37 * hash) + LANDAREA_FIELD_NUMBER;
    hash = (53 * hash) + getLandArea();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getValue()));
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.Propertie parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Propertie parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Propertie parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Propertie parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Propertie parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.Propertie parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.Propertie parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Propertie parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Propertie parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.Propertie parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.Propertie parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.Propertie parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.Propertie prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.Propertie}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Propertie)
      proto.PropertieOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.PropertieOuterClass.internal_static_proto_Propertie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.PropertieOuterClass.internal_static_proto_Propertie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Propertie.class, proto.Propertie.Builder.class);
    }

    // Construct using proto.Propertie.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      title_ = "";

      address_ = "";

      numberBedroom_ = 0;

      numberGarage_ = 0;

      buildingArea_ = 0;

      landArea_ = 0;

      value_ = 0D;

      type_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.PropertieOuterClass.internal_static_proto_Propertie_descriptor;
    }

    @java.lang.Override
    public proto.Propertie getDefaultInstanceForType() {
      return proto.Propertie.getDefaultInstance();
    }

    @java.lang.Override
    public proto.Propertie build() {
      proto.Propertie result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.Propertie buildPartial() {
      proto.Propertie result = new proto.Propertie(this);
      result.id_ = id_;
      result.title_ = title_;
      result.address_ = address_;
      result.numberBedroom_ = numberBedroom_;
      result.numberGarage_ = numberGarage_;
      result.buildingArea_ = buildingArea_;
      result.landArea_ = landArea_;
      result.value_ = value_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.Propertie) {
        return mergeFrom((proto.Propertie)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.Propertie other) {
      if (other == proto.Propertie.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        onChanged();
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (other.getNumberBedroom() != 0) {
        setNumberBedroom(other.getNumberBedroom());
      }
      if (other.getNumberGarage() != 0) {
        setNumberGarage(other.getNumberGarage());
      }
      if (other.getBuildingArea() != 0) {
        setBuildingArea(other.getBuildingArea());
      }
      if (other.getLandArea() != 0) {
        setLandArea(other.getLandArea());
      }
      if (other.getValue() != 0D) {
        setValue(other.getValue());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.Propertie parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.Propertie) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      title_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      
      title_ = getDefaultInstance().getTitle();
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      title_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 3;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 3;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 3;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 3;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private int numberBedroom_ ;
    /**
     * <code>int32 numberBedroom = 4;</code>
     * @return The numberBedroom.
     */
    public int getNumberBedroom() {
      return numberBedroom_;
    }
    /**
     * <code>int32 numberBedroom = 4;</code>
     * @param value The numberBedroom to set.
     * @return This builder for chaining.
     */
    public Builder setNumberBedroom(int value) {
      
      numberBedroom_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberBedroom = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberBedroom() {
      
      numberBedroom_ = 0;
      onChanged();
      return this;
    }

    private int numberGarage_ ;
    /**
     * <code>int32 numberGarage = 5;</code>
     * @return The numberGarage.
     */
    public int getNumberGarage() {
      return numberGarage_;
    }
    /**
     * <code>int32 numberGarage = 5;</code>
     * @param value The numberGarage to set.
     * @return This builder for chaining.
     */
    public Builder setNumberGarage(int value) {
      
      numberGarage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 numberGarage = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumberGarage() {
      
      numberGarage_ = 0;
      onChanged();
      return this;
    }

    private int buildingArea_ ;
    /**
     * <code>int32 buildingArea = 6;</code>
     * @return The buildingArea.
     */
    public int getBuildingArea() {
      return buildingArea_;
    }
    /**
     * <code>int32 buildingArea = 6;</code>
     * @param value The buildingArea to set.
     * @return This builder for chaining.
     */
    public Builder setBuildingArea(int value) {
      
      buildingArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buildingArea = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildingArea() {
      
      buildingArea_ = 0;
      onChanged();
      return this;
    }

    private int landArea_ ;
    /**
     * <code>int32 landArea = 7;</code>
     * @return The landArea.
     */
    public int getLandArea() {
      return landArea_;
    }
    /**
     * <code>int32 landArea = 7;</code>
     * @param value The landArea to set.
     * @return This builder for chaining.
     */
    public Builder setLandArea(int value) {
      
      landArea_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 landArea = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLandArea() {
      
      landArea_ = 0;
      onChanged();
      return this;
    }

    private double value_ ;
    /**
     * <code>double value = 8;</code>
     * @return The value.
     */
    public double getValue() {
      return value_;
    }
    /**
     * <code>double value = 8;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(double value) {
      
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double value = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = 0D;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.proto.Propertie.Type type = 9;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.Propertie.Type type = 9;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Propertie.Type type = 9;</code>
     * @return The type.
     */
    public proto.Propertie.Type getType() {
      @SuppressWarnings("deprecation")
      proto.Propertie.Type result = proto.Propertie.Type.valueOf(type_);
      return result == null ? proto.Propertie.Type.UNRECOGNIZED : result;
    }
    /**
     * <code>.proto.Propertie.Type type = 9;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(proto.Propertie.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.proto.Propertie.Type type = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.Propertie)
  }

  // @@protoc_insertion_point(class_scope:proto.Propertie)
  private static final proto.Propertie DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.Propertie();
  }

  public static proto.Propertie getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Propertie>
      PARSER = new com.google.protobuf.AbstractParser<Propertie>() {
    @java.lang.Override
    public Propertie parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Propertie(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Propertie> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Propertie> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.Propertie getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

