// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

public final class PropertieOuterClass {
  private PropertieOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Propertie_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Propertie_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreatePropertieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreatePropertieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CreatePropertieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CreatePropertieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdatePropertieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdatePropertieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_UpdatePropertieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_UpdatePropertieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetPropertieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetPropertieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_GetPropertieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_GetPropertieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeletePropertieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeletePropertieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_DeletePropertieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_DeletePropertieResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListAllPropertieRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListAllPropertieRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ListAllPropertieResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ListAllPropertieResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017propertie.proto\022\005proto\"\233\001\n\tPropertie\022\n" +
      "\n\002id\030\001 \001(\005\022\r\n\005title\030\002 \001(\t\022\017\n\007address\030\003 \001" +
      "(\t\022\025\n\rnumberBedroom\030\004 \001(\005\022\024\n\014numberGarag" +
      "e\030\005 \001(\005\022\024\n\014buildingArea\030\006 \001(\005\022\020\n\010landAre" +
      "a\030\007 \001(\005\022\r\n\005value\030\010 \001(\001\"=\n\026CreateProperti" +
      "eRequest\022#\n\tpropertie\030\001 \001(\0132\020.proto.Prop" +
      "ertie\">\n\027CreatePropertieResponse\022#\n\tprop" +
      "ertie\030\001 \001(\0132\020.proto.Propertie\"=\n\026UpdateP" +
      "ropertieRequest\022#\n\tpropertie\030\001 \001(\0132\020.pro" +
      "to.Propertie\">\n\027UpdatePropertieResponse\022" +
      "#\n\tpropertie\030\001 \001(\0132\020.proto.Propertie\"*\n\023" +
      "GetPropertieRequest\022\023\n\013propertieId\030\001 \001(\005" +
      "\";\n\024GetPropertieResponse\022#\n\tpropertie\030\001 " +
      "\001(\0132\020.proto.Propertie\"-\n\026DeletePropertie" +
      "Request\022\023\n\013propertieId\030\001 \001(\005\".\n\027DeletePr" +
      "opertieResponse\022\023\n\013propertieId\030\001 \001(\005\"\031\n\027" +
      "ListAllPropertieRequest\"?\n\030ListAllProper" +
      "tieResponse\022#\n\tpropertie\030\001 \003(\0132\020.proto.P" +
      "ropertie2\246\003\n\020PropertieService\022P\n\017CreateP" +
      "ropertie\022\035.proto.CreatePropertieRequest\032" +
      "\036.proto.CreatePropertieResponse\022P\n\017Delet" +
      "ePropertie\022\035.proto.DeletePropertieReques" +
      "t\032\036.proto.DeletePropertieResponse\022G\n\014Get" +
      "Propertie\022\032.proto.GetPropertieRequest\032\033." +
      "proto.GetPropertieResponse\022S\n\020ListAllPro" +
      "pertie\022\036.proto.ListAllPropertieRequest\032\037" +
      ".proto.ListAllPropertieResponse\022P\n\017Updat" +
      "ePropertie\022\035.proto.UpdatePropertieReques" +
      "t\032\036.proto.UpdatePropertieResponseB\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Propertie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Propertie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Propertie_descriptor,
        new java.lang.String[] { "Id", "Title", "Address", "NumberBedroom", "NumberGarage", "BuildingArea", "LandArea", "Value", });
    internal_static_proto_CreatePropertieRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CreatePropertieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreatePropertieRequest_descriptor,
        new java.lang.String[] { "Propertie", });
    internal_static_proto_CreatePropertieResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CreatePropertieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CreatePropertieResponse_descriptor,
        new java.lang.String[] { "Propertie", });
    internal_static_proto_UpdatePropertieRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_UpdatePropertieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdatePropertieRequest_descriptor,
        new java.lang.String[] { "Propertie", });
    internal_static_proto_UpdatePropertieResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_UpdatePropertieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_UpdatePropertieResponse_descriptor,
        new java.lang.String[] { "Propertie", });
    internal_static_proto_GetPropertieRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_GetPropertieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetPropertieRequest_descriptor,
        new java.lang.String[] { "PropertieId", });
    internal_static_proto_GetPropertieResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_GetPropertieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_GetPropertieResponse_descriptor,
        new java.lang.String[] { "Propertie", });
    internal_static_proto_DeletePropertieRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_DeletePropertieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeletePropertieRequest_descriptor,
        new java.lang.String[] { "PropertieId", });
    internal_static_proto_DeletePropertieResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_proto_DeletePropertieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_DeletePropertieResponse_descriptor,
        new java.lang.String[] { "PropertieId", });
    internal_static_proto_ListAllPropertieRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_proto_ListAllPropertieRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListAllPropertieRequest_descriptor,
        new java.lang.String[] { });
    internal_static_proto_ListAllPropertieResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_proto_ListAllPropertieResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ListAllPropertieResponse_descriptor,
        new java.lang.String[] { "Propertie", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
