// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: propertie.proto

package proto;

public interface PropertieOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Propertie)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string address = 3;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 3;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 numberBedroom = 4;</code>
   * @return The numberBedroom.
   */
  int getNumberBedroom();

  /**
   * <code>int32 numberGarage = 5;</code>
   * @return The numberGarage.
   */
  int getNumberGarage();

  /**
   * <code>int32 buildingArea = 6;</code>
   * @return The buildingArea.
   */
  int getBuildingArea();

  /**
   * <code>int32 landArea = 7;</code>
   * @return The landArea.
   */
  int getLandArea();

  /**
   * <code>double value = 8;</code>
   * @return The value.
   */
  double getValue();
}
