/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.forms;

import client.PropertieClientImpl;
import client.models.PropertieModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import proto.Propertie;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    List<PropertieModel> myList = new ArrayList<PropertieModel>();
    PropertieModel propertieForm = new PropertieModel();
    PropertieClientImpl client = new PropertieClientImpl();
    Propertie.Builder propertieBuilderForm = Propertie.newBuilder();

    public Main() {
        initComponents();
        this.fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtProperties = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxTitle = new javax.swing.JTextField();
        jtxAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbType = new javax.swing.JComboBox<>();
        jsNumberBedrooms = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jsNumberGarages = new javax.swing.JSpinner();
        jtxLandArea = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxBuildedArea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxValue = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbSave = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jbNew = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProperties);

        jLabel1.setText("Titulo");

        jtxTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxTitleActionPerformed(evt);
            }
        });

        jLabel2.setText("Endereco");

        jLabel3.setText("Qtd Quartos");

        jLabel4.setText("Tipo do Imovel");

        jcbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa" }));

        jLabel5.setText("Qtd Garagens");

        jLabel6.setText("Area do terreno");

        jLabel7.setText("Area construida");

        jLabel8.setText("Preco");

        jbSave.setText("Salvar");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        jbClear.setText("Limpar");
        jbClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setText("Cadastro de Imoveis");

        jbNew.setText("Novo");
        jbNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewActionPerformed(evt);
            }
        });

        jbEdit.setText("Editar");
        jbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditActionPerformed(evt);
            }
        });

        jbDelete.setText("Deletar");
        jbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(297, 297, 297))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jtxLandArea, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jtxTitle)
                                    .addComponent(jLabel2)
                                    .addComponent(jtxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7)
                            .addComponent(jtxBuildedArea, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbSave)
                                .addGap(26, 26, 26)
                                .addComponent(jbClear))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jsNumberBedrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jsNumberGarages, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addComponent(jcbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jtxValue, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDelete)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsNumberBedrooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jsNumberGarages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxLandArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxBuildedArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSave)
                    .addComponent(jbClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNew)
                    .addComponent(jbEdit)
                    .addComponent(jbDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        Propertie toSave = propertieBuilderForm
                .setTitle(jtxTitle.getText())
                .setAddress(jtxAddress.getText())
                .setNumberBedroom(Integer.parseInt(jsNumberBedrooms.getValue().toString()))
                .setNumberGarage(Integer.parseInt(jsNumberGarages.getValue().toString()))
                .setLandArea(Integer.parseInt(jtxLandArea.getText()))
                .setValue(Double.parseDouble(jtxValue.getText()))
                .setBuildingArea(Integer.parseInt(jtxBuildedArea.getText()))
                .setType(jcbType.getSelectedItem().equals("Apartamento")?Propertie.Type.APARTMENT:Propertie.Type.HOUSE)
                .build();
        System.out.println(toSave.getType());
        if (toSave.getId() == 0) {
            client.createPropertie(toSave);
        } else {
            client.updatePropertie(toSave);
        }
        JOptionPane.showMessageDialog(null, "Salvo com sucesso!", "Sucesso", JOptionPane.PLAIN_MESSAGE);
        clearForm();
        fillTable();
        

    }//GEN-LAST:event_jbSaveActionPerformed

    private void jbClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jbClearActionPerformed

    private void jtxTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxTitleActionPerformed

    private void jbNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewActionPerformed
        // TODO add your handling code here:
        propertieBuilderForm = Propertie.newBuilder();
        clearForm();
    }//GEN-LAST:event_jbNewActionPerformed

    private void jbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditActionPerformed
        // TODO add your handling code here:
        PropertieModel propertie;
        if (jtProperties.getSelectedRow() != -1) {

            propertie = (PropertieModel) myList.get(jtProperties.getSelectedRow());
            propertieBuilderForm = Propertie.newBuilder().setId(propertie.getId());
            jtxValue.setText(propertie.getValue().toString());
            jtxAddress.setText(propertie.getAddress());
            jtxBuildedArea.setText(propertie.getBuildedArea().toString());
            jtxLandArea.setText(propertie.getLandArea().toString());
            jtxTitle.setText(propertie.getTitle());
            jsNumberBedrooms.setValue(propertie.getNumberBedroom());
            jsNumberGarages.setValue(propertie.getNumberGarage());
            jcbType.setSelectedItem(propertie.getType());

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbEditActionPerformed

    private void jbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteActionPerformed
        PropertieModel propertie;
        if (jtProperties.getSelectedRow() != -1) {

            propertie = (PropertieModel) myList.get(jtProperties.getSelectedRow());
            Propertie toDelete = toPropertie(propertie);
            client.deletePropertie(propertie.getId());
            JOptionPane.showMessageDialog(null, "Apagado com sucesso!", "Sucesso", JOptionPane.PLAIN_MESSAGE);
            fillTable();
            clearForm();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void clearForm() {
        jtxValue.setText("");
        jtxAddress.setText("");
        jtxBuildedArea.setText("");
        jtxLandArea.setText("");
        jtxTitle.setText("");
        jsNumberBedrooms.setValue(0);
        jsNumberGarages.setValue(0);
        propertieBuilderForm = Propertie.newBuilder();
    }

    public void fillTable() {

        myList = this.toPropertieModelList(client.listAllPropertie());
        MyTableModel mtb = new MyTableModel(PropertieModel.class, myList, jtProperties);
        jtProperties.setModel(mtb);
    }

    private List<PropertieModel> toPropertieModelList(List<Propertie> list) {
        List<PropertieModel> toReturn = new ArrayList<>();
        for (Propertie prop : list) {
            toReturn.add(toPropertieModel(prop));
        }
        return toReturn;
    }

    private PropertieModel toPropertieModel(Propertie prop) {

        return new PropertieModel(prop.getId(), prop.getTitle(), prop.getAddress(), prop.getType().equals(Propertie.Type.APARTMENT)?"Apartamento":"Casa", prop.getNumberBedroom(), prop.getNumberGarage(), prop.getLandArea(), prop.getBuildingArea(), prop.getValue());

    }

    private Propertie toPropertie(PropertieModel prop) {

        return Propertie.newBuilder()
                .setId(prop.getId())
                .setTitle(prop.getTitle())
                .setAddress(prop.getAddress())
                .setNumberBedroom(prop.getNumberBedroom())
                .setNumberGarage(prop.getNumberGarage())
                .setLandArea(prop.getLandArea())
                .setValue(prop.getValue())
                .setType(jcbType.getSelectedItem().equals("Apartamento")?Propertie.Type.APARTMENT:Propertie.Type.HOUSE)
                .build();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbEdit;
    private javax.swing.JButton jbNew;
    private javax.swing.JButton jbSave;
    private javax.swing.JComboBox<String> jcbType;
    private javax.swing.JSpinner jsNumberBedrooms;
    private javax.swing.JSpinner jsNumberGarages;
    private javax.swing.JTable jtProperties;
    private javax.swing.JTextField jtxAddress;
    private javax.swing.JTextField jtxBuildedArea;
    private javax.swing.JTextField jtxLandArea;
    private javax.swing.JTextField jtxTitle;
    private javax.swing.JTextField jtxValue;
    // End of variables declaration//GEN-END:variables
}
